### ISSUE TITLE
what are dataset_utils and train modules in RETRAINING.ipynb supposed to be?

### ISSUE THREAD

**Issue by MateoG42** [GAMELab-UGA/NorthernBobwhiteCNN#1]
I tried running the RETRAINING.ipynb from the CoveyCNN.zip file but was unable to import dataset_utils. I tried searching around but couldn't figure out what module it's supposed to be. Is this a module on conda/pip or a missing file?

Also, looking through the import list I'm not sure what train is supposed to be.

![image](https://github.com/GAMELab-UGA/NorthernBobwhiteCNN/assets/89881849/4b43dcb7-30f3-43fd-b8a9-674641bffdff)

**Comment by victorianolan8** [comment]
Apologies, there were some missing files here. Please see the new zipped folder:
https://github.com/GAMELab-UGA/NorthernBobwhiteCNN/blob/main/CoveyCNN_GITHUB.zip
