### ISSUE TITLE
utils.py is missing from CoveyCNN.zip

### ISSUE THREAD

**Issue by MateoG42** [GAMELab-UGA/NorthernBobwhiteCNN#2]
Running the notebooks provided in CoveyCNN.zip results in an error where utils.py appears to be missing. Using the utils.py in the PythonCode folder also does not work and results in these errors.
![Screenshot 2023-07-18 145100](https://github.com/GAMELab-UGA/NorthernBobwhiteCNN/assets/89881849/ef4adbab-0457-4f0a-9d38-6fd39b80c9f8)
![Screenshot 2023-07-18 145716](https://github.com/GAMELab-UGA/NorthernBobwhiteCNN/assets/89881849/f17a960b-7ad8-4b1f-9e26-bb13c459c37b)

**Comment by victorianolan8** [comment]
Apologies for the missing files. A new zipped folder containing all the necessary files has been added now:
https://github.com/GAMELab-UGA/NorthernBobwhiteCNN/blob/main/CoveyCNN_GITHUB.zip
